source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'PYFBaseApplication' do
  use_frameworks!
  pod 'PolyvVodSDK', '2.16.6'
end

#pre_install do |installer|
#Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
#end

#post_install do |installer|
#    installer.pods_project.build_configurations.each do |config|    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#  end
#end
